export type DatingCategory =
  | 'Frame' | 'Approach' | 'Conversation' | 'Texting' | 'Building Comfort'
  | 'Making Her Feel Special' | 'Emotional Contrast' | 'Scarcity'
  | 'Taking Her Home' | 'Relationship' | 'Intimacy' | 'Closing';

export type DatingPhase = 'before-you-go' | 'opening' | 'conversation' | 'escalation' | 'closing' | 'ongoing';

export interface DatingCard {
  id: string;
  category: DatingCategory;
  phase: DatingPhase;
  cheat_sheet_essential: boolean;
  short_form: string;
  long_form: string;
}

export const PHASE_LABELS: Record<DatingPhase, string> = {
  'before-you-go': 'Before You Go',
  opening: 'Opening',
  conversation: 'Conversation',
  escalation: 'Escalation',
  closing: 'Closing',
  ongoing: 'Ongoing',
};

export const CATEGORY_ORDER: DatingCategory[] = [
  'Frame', 'Approach', 'Conversation', 'Building Comfort', 'Making Her Feel Special',
  'Texting', 'Emotional Contrast', 'Scarcity', 'Closing', 'Taking Her Home', 'Relationship', 'Intimacy',
];

export const PHASE_ORDER: DatingPhase[] = ['before-you-go', 'opening', 'conversation', 'escalation', 'closing', 'ongoing'];

export const DATING_CARDS: DatingCard[] = [
  // ---- Frame ----
  {
    id: 'ground-rules',
    category: 'Frame',
    phase: 'before-you-go',
    cheat_sheet_essential: false,
    short_form: 'None of this is a trick — it\'s a skill, and grace in rejection is the most attractive trait of all.',
    long_form: 'None of this works as a trick, and all of it works as a skill. You\'re not extracting anything from anyone — you\'re becoming someone women genuinely enjoy being around, and being direct about your interest. Read her signals honestly: if she\'s engaged, continue; if she\'s polite-but-flat, wish her a good day and exit gracefully. Grace in rejection is the single most attractive trait you can build, because it means you were never desperate.',
  },
  {
    id: 'frame-reality',
    category: 'Frame',
    phase: 'before-you-go',
    cheat_sheet_essential: false,
    short_form: 'Frame is whose reality the interaction runs on — keep yours by not auditioning for approval.',
    long_form: 'Frame is whose reality the interaction runs on. Two people meet with two versions of "what\'s happening here" — attraction, banter, and outcomes all get decided by whichever frame wins. You keep yours by not flinching, over-explaining, or auditioning for the other person\'s approval.',
  },
  {
    id: 'frame-pedestal',
    category: 'Frame',
    phase: 'before-you-go',
    cheat_sheet_essential: true,
    short_form: 'Never put her on a pedestal — you approach, you don\'t apply.',
    long_form: 'The instant you treat someone as above you — more impressive, more valuable, someone you need to win over — you\'ve handed them the frame and it shows in every word after. She\'s a person you\'re getting to know, not a judge scoring you. You approach; you don\'t apply.',
  },
  {
    id: 'frame-prize',
    category: 'Frame',
    phase: 'before-you-go',
    cheat_sheet_essential: false,
    short_form: 'You\'re the prize too — this is a two-way evaluation, not an interview.',
    long_form: 'Not arrogance — accuracy. You bring a full life, standards, and things you won\'t compromise on. The right mindset going in isn\'t "I hope she likes me," it\'s "let\'s see if we actually vibe" — a two-way evaluation, not an interview where only you\'re being assessed.',
  },
  {
    id: 'frame-qualify',
    category: 'Frame',
    phase: 'conversation',
    cheat_sheet_essential: true,
    short_form: 'Qualify her back — check if SHE\'S worth your time, don\'t just perform for her.',
    long_form: 'Instead of stacking reasons she should like you, ask questions that check if SHE\'S someone worth your time: her humour, her ambition, how she treats people. The switch from "please be impressed" to "let\'s see if you\'re interesting" changes your entire energy — and it\'s usually the difference people can\'t name but feel instantly.',
  },
  {
    id: 'frame-rejection',
    category: 'Frame',
    phase: 'before-you-go',
    cheat_sheet_essential: true,
    short_form: 'A no is poor fit found early, not a loss — stay level either way.',
    long_form: 'A "no" doesn\'t mean you lost — it means poor fit, found early, cheaply. Frame stays intact when outcomes don\'t define your worth. This is why the men with real frame are calm about rejection: it was never a referendum on them.',
  },
  {
    id: 'frame-small-moments',
    category: 'Frame',
    phase: 'conversation',
    cheat_sheet_essential: false,
    short_form: 'Frame breaks in small moments — don\'t over-explain, don\'t rush to fix silence, don\'t fold.',
    long_form: 'Changing your opinion because she disagreed, over-explaining a joke that didn\'t land, rushing to fix a silence, apologising for existing — these tiny concessions leak frame faster than any single big mistake. Hold your positions lightly and calmly; you can be flexible without being someone who folds.',
  },
  {
    id: 'frame-standards',
    category: 'Frame',
    phase: 'before-you-go',
    cheat_sheet_essential: true,
    short_form: 'Decide your standards before you go out — and hold the line regardless of attraction.',
    long_form: 'Decide beforehand what you won\'t tolerate — disrespect, flakiness, disappearing acts — and hold that line regardless of how attracted you are. A man with standards he actually enforces is rarer and more magnetic than a man with a perfect opening line.',
  },

  // ---- Approach ----
  {
    id: 'approach-3-seconds',
    category: 'Approach',
    phase: 'opening',
    cheat_sheet_essential: true,
    short_form: 'Within 3 seconds of noticing her — hesitation builds a story in your head. See, decide, go.',
    long_form: 'Within 3 seconds of noticing her — hesitation builds a story in your head and weirdness in your walk-up. See, decide, go.',
  },
  {
    id: 'approach-angle',
    category: 'Approach',
    phase: 'opening',
    cheat_sheet_essential: false,
    short_form: 'Front or side, never behind — comfortable distance, relaxed pace.',
    long_form: 'Approach from an angle she can see, comfortable distance, relaxed pace. In daytime, a slight pause + "excuse me" is perfect.',
  },
  {
    id: 'approach-direct',
    category: 'Approach',
    phase: 'opening',
    cheat_sheet_essential: true,
    short_form: 'Be direct and own it — direct beats routines because it shows nerve.',
    long_form: '"This is random, but I saw you and thought you looked interesting — I had to say hi. I\'m Roy." Direct beats routines because it demonstrates the scarcest asset: nerve.',
  },
  {
    id: 'approach-voice',
    category: 'Approach',
    phase: 'opening',
    cheat_sheet_essential: false,
    short_form: 'Voice slow, volume up, smile real — if you feel shaky, slow down 20% more.',
    long_form: 'Nerves make guys rush and mumble. If you feel shaky, slow down 20% more.',
  },
  {
    id: 'approach-situational',
    category: 'Approach',
    phase: 'opening',
    cheat_sheet_essential: false,
    short_form: 'Situational openers work too — comment on the shared moment, then transition to your name.',
    long_form: 'Comment on the thing you\'re both experiencing (the queue, the playlist, her book) then transition: "I\'m Roy, by the way."',
  },
  {
    id: 'nightsout-logistics',
    category: 'Approach',
    phase: 'before-you-go',
    cheat_sheet_essential: false,
    short_form: 'Go earlier than the crowd, small group of 2-3, stay light on drink.',
    long_form: 'Go earlier than the crowd (11pm energy is friendlier than 1am chaos), small group of 2-3 (big packs are unapproachable and distracting), and stay light on drink — 2 drinks of social lubricant, never sloppy. You cannot run any of this drunk.',
  },
  {
    id: 'nightsout-warmup',
    category: 'Approach',
    phase: 'opening',
    cheat_sheet_essential: true,
    short_form: 'Warm up immediately — talk to everyone for the first 30 min before you approach.',
    long_form: 'Talk to EVERYONE for the first 30 min — bouncers, bartenders, groups of guys, everyone. You\'re not approaching yet; you\'re getting your social engine warm so the first real approach isn\'t cold.',
  },
  {
    id: 'nightsout-positioning',
    category: 'Approach',
    phase: 'opening',
    cheat_sheet_essential: true,
    short_form: 'Positioning beats approaching — stand where traffic flows, watch for the held look.',
    long_form: 'Stand where traffic flows — near the bar, not hidden in a booth. Eye contact + smile at girls as they pass; if she holds it or looks back twice, that\'s your green light and half the work is done.',
  },
  {
    id: 'nightsout-loud-venue',
    category: 'Approach',
    phase: 'opening',
    cheat_sheet_essential: false,
    short_form: 'Loud venue = simple and close. Skip clever openers, lean in, position side-by-side.',
    long_form: 'Forget clever openers, they can\'t hear you. Warm smile, lean toward her ear: "I had to come say hi — I\'m Roy." Then physically position side-by-side (easier than shouting face-to-face).',
  },
  {
    id: 'nightsout-group',
    category: 'Approach',
    phase: 'opening',
    cheat_sheet_essential: false,
    short_form: 'Handle the group — her friends decide your fate. Greet them early, win a smile.',
    long_form: 'Her friends decide your fate. Greet them early ("are you looking after her tonight? good"), win a smile from them, then turn back. Ignoring friends = friends extract her in 5 minutes.',
  },

  // ---- Conversation ----
  {
    id: 'speak-statements',
    category: 'Conversation',
    phase: 'conversation',
    cheat_sheet_essential: true,
    short_form: 'Statements and assumptions, not interviews — invite her to play, not autopilot.',
    long_form: '"You seem like the friend who plans the whole trip" invites her to play. "What do you do?" invites autopilot.',
  },
  {
    id: 'speak-tease',
    category: 'Conversation',
    phase: 'conversation',
    cheat_sheet_essential: false,
    short_form: 'Tease lightly, warmly — confidence, never at her insecurities.',
    long_form: 'Playful disagreement and gentle teasing ("you\'re trouble, I can tell") signals confidence — always with a smile, never at her insecurities.',
  },
  {
    id: 'speak-pushpull',
    category: 'Conversation',
    phase: 'conversation',
    cheat_sheet_essential: true,
    short_form: 'Push-pull rhythm — show interest, then playfully withdraw it. Tension over flatness.',
    long_form: 'Show interest, then playfully withdraw it: "You\'re actually funny… this might be a terrible idea." Tension is what separates flirting from friendliness.',
  },
  {
    id: 'speak-eye-contact',
    category: 'Conversation',
    phase: 'conversation',
    cheat_sheet_essential: false,
    short_form: 'Hold eye contact a beat longer than friendly, with a slight smile.',
    long_form: 'Most attraction is communicated in the look, not the words.',
  },
  {
    id: 'speak-intent',
    category: 'Conversation',
    phase: 'conversation',
    cheat_sheet_essential: false,
    short_form: 'Don\'t hide your intent — visible interest plus being unbothered about the outcome.',
    long_form: 'You\'re not her buddy. Flirting = your interest is visible AND you\'re unbothered about the outcome.',
  },
  {
    id: 'nightsout-quieter',
    category: 'Conversation',
    phase: 'escalation',
    cheat_sheet_essential: false,
    short_form: 'Move somewhere quieter as an invitation, never a pull.',
    long_form: '"It\'s way too loud here — let\'s grab a drink at the bar / get some air by the smoking area." Venue changes within the night build hours of comfort in minutes. Always an invitation, never a pull.',
  },
  {
    id: 'connection-heard',
    category: 'Conversation',
    phase: 'conversation',
    cheat_sheet_essential: false,
    short_form: 'Make her feel heard specifically — a remembered detail beats generic compliments.',
    long_form: 'Generic compliments bounce off; specific callbacks stick. "You said last week you were dreading that presentation — how did it actually go?" is worth more than a hundred "you\'re gorgeous" texts.',
  },
  {
    id: 'connection-pace',
    category: 'Conversation',
    phase: 'escalation',
    cheat_sheet_essential: false,
    short_form: 'Escalate at HER pace, not a script\'s — match the energy she\'s giving back.',
    long_form: 'Depth, flirting, touch, plans — each step should match the energy she\'s giving back. If she opens up, meet her there. If she keeps it light, stay light and let it build. Scripted sequences ignore the person in front of you, and it shows.',
  },
  {
    id: 'connection-signals',
    category: 'Conversation',
    phase: 'conversation',
    cheat_sheet_essential: true,
    short_form: 'Read actual signals — interested asks back and stays close, polite exits when convenient.',
    long_form: 'Interested looks like: she asks questions back, extends conversations, remembers your details, finds reasons to stay near. Polite looks like: short answers, no questions, exits when convenient. Believe the pattern, not the one ambiguous moment — and never argue with a no.',
  },
  {
    id: 'connection-surprise',
    category: 'Conversation',
    phase: 'conversation',
    cheat_sheet_essential: false,
    short_form: 'Let her surprise you — curiosity about who she actually is is rare and magnetic.',
    long_form: 'Curiosity about who she actually is — not a category of girl — is rare enough to be magnetic. The guys who connect are the ones who update what they think in real time instead of running a routine.',
  },

  // ---- Building Comfort ----
  {
    id: 'comfort-depth',
    category: 'Building Comfort',
    phase: 'conversation',
    cheat_sheet_essential: false,
    short_form: 'Trade depth gradually — share something real first, vulnerability invites hers.',
    long_form: 'Share something real about yourself first (dreams, family, an embarrassing story) — vulnerability from strength invites hers.',
  },
  {
    id: 'comfort-listen',
    category: 'Building Comfort',
    phase: 'conversation',
    cheat_sheet_essential: false,
    short_form: 'Listen like it\'s a skill — remember details and call back to them later.',
    long_form: 'Remember details and call back to them later ("wait — is this the sister from the Spain story?"). Callbacks build an inside world between you two.',
  },
  {
    id: 'comfort-us-frame',
    category: 'Building Comfort',
    phase: 'conversation',
    cheat_sheet_essential: false,
    short_form: 'Us-frame — little conspiracies create "us vs the room."',
    long_form: 'Little conspiracies: "we\'re definitely judging this DJ together." Shared jokes create "us vs the room."',
  },
  {
    id: 'comfort-boring',
    category: 'Building Comfort',
    phase: 'conversation',
    cheat_sheet_essential: false,
    short_form: 'Comfort ≠ boring — keep flirting while going deeper.',
    long_form: 'Keep flirting while going deeper. Deep + zero tension = friend zone; tension + zero depth = forgettable.',
  },

  // ---- Making Her Feel Special ----
  {
    id: 'special-chose',
    category: 'Making Her Feel Special',
    phase: 'conversation',
    cheat_sheet_essential: false,
    short_form: 'Compliment what she chose, not just what she was born with.',
    long_form: 'Her taste, her humour, her ambition, the way she tells a story. "You light up when you talk about that" lands deeper than "you\'re pretty."',
  },
  {
    id: 'special-specific',
    category: 'Making Her Feel Special',
    phase: 'conversation',
    cheat_sheet_essential: false,
    short_form: 'Specific beats generic, always — one precise observation outweighs ten "amazing"s.',
    long_form: 'One precise observation about her ("you ask better questions than anyone I\'ve met this month") outweighs ten "you\'re amazing"s.',
  },
  {
    id: 'special-presence',
    category: 'Making Her Feel Special',
    phase: 'conversation',
    cheat_sheet_essential: false,
    short_form: 'Full presence is the gift — phone away, body turned to her, unhurried.',
    long_form: 'Phone away, body turned to her, unhurried. In a distracted world, undivided attention feels rare because it is.',
  },
  {
    id: 'special-followthrough',
    category: 'Making Her Feel Special',
    phase: 'ongoing',
    cheat_sheet_essential: false,
    short_form: 'Remember and follow through — reliability is romance.',
    long_form: 'If she mentions an exam, a trip, a hard week — ask about it next time unprompted. Reliability is romance.',
  },

  // ---- Texting ----
  {
    id: 'text-mirror',
    category: 'Texting',
    phase: 'ongoing',
    cheat_sheet_essential: true,
    short_form: 'Match her length and pace roughly — mirroring reads as calibrated, not anxious.',
    long_form: 'She sends two lines, you send around two lines. She takes an hour, you don\'t need to reply in 30 seconds. Mirroring reads as calibrated; triple-texting reads as anxious. One follow-up max, then let it breathe.',
  },
  {
    id: 'text-intent',
    category: 'Texting',
    phase: 'ongoing',
    cheat_sheet_essential: false,
    short_form: 'Text with intent — every message should have a job: a question, a bit, or a plan.',
    long_form: '"haha yeah" is a dead-end — if you have nothing to add, that\'s the moment to propose something instead.',
  },
  {
    id: 'text-specific',
    category: 'Texting',
    phase: 'ongoing',
    cheat_sheet_essential: false,
    short_form: 'Specificity beats "hey, how\'s it going" — a callback lands 10x harder.',
    long_form: 'Callback to your conversation ("saw a guy order the thing you swore you\'d never admit you like") lands 10× harder than a generic check-in. Specific = you remembered = you care.',
  },
  {
    id: 'text-honest',
    category: 'Texting',
    phase: 'ongoing',
    cheat_sheet_essential: false,
    short_form: 'Don\'t perform interest you don\'t have — hot-and-cold reads worse than honest and direct.',
    long_form: 'If you like her, text like it. If you\'re unsure, don\'t manufacture daily conversation out of obligation — inconsistency is the real turn-off.',
  },
  {
    id: 'text-plan',
    category: 'Texting',
    phase: 'ongoing',
    cheat_sheet_essential: true,
    short_form: 'The plan is the point — texting exists to get to the date, not to stay texting.',
    long_form: 'Two or three good exchanges, then: "Thursday, that ramen place you doubted — 7?" Prolonged pen-pal phases kill more connections than bad openers ever have.',
  },

  // ---- Emotional Contrast ----
  {
    id: 'rollercoaster-principle',
    category: 'Emotional Contrast',
    phase: 'escalation',
    cheat_sheet_essential: false,
    short_form: 'Emotion is the memory glue — a range of feelings beats one pleasant note held for hours.',
    long_form: 'People remember how you made them FEEL, and a range of feelings beats one pleasant note held for hours. A conversation that goes laughter → mock outrage → genuine depth → back to laughter is an experience; polite agreement is wallpaper. This isn\'t about hurting anyone — it\'s about being emotionally alive instead of flat.',
  },
  {
    id: 'rollercoaster-contrast',
    category: 'Emotional Contrast',
    phase: 'escalation',
    cheat_sheet_essential: false,
    short_form: 'Contrast is the mechanism — tease her, then drop a sincere specific compliment.',
    long_form: 'Tease her, THEN drop a sincere specific compliment — the sincerity lands 5× harder against the teasing backdrop. Be playfully disagreeable, then genuinely fascinated by her answer. All warmth = friend. All tease = clown. The switch between them = tension.',
  },
  {
    id: 'rollercoaster-locations',
    category: 'Emotional Contrast',
    phase: 'escalation',
    cheat_sheet_essential: true,
    short_form: 'Take her through emotional locations — funny, competitive, nostalgic, dreamy, sincere.',
    long_form: 'Within one conversation, visit: funny (banter, absurd hypotheticals), competitive ("you\'d lose and you know it"), nostalgic ("what did tiny [her name] want to be?"), dreamy (travel, ambitions), conspiratorial (whispered judging of the room), sincere (one real moment). Each shift feels like time passing together — this is why one great conversation can feel like three dates.',
  },
  {
    id: 'rollercoaster-pushpull',
    category: 'Emotional Contrast',
    phase: 'escalation',
    cheat_sheet_essential: false,
    short_form: 'Push-pull, the clean version — one line of push and pull, used sparingly, always with a grin.',
    long_form: '"You\'re actually terrible news… and I kind of like it." Push (playful distance) + pull (real interest) in one line. Use sparingly — one or two per conversation, always with a grin, never targeting real insecurities.',
  },
  {
    id: 'rollercoaster-dates',
    category: 'Emotional Contrast',
    phase: 'escalation',
    cheat_sheet_essential: false,
    short_form: 'Plan dates that ARE rollercoasters — the excitement gets attributed to you.',
    long_form: 'Adrenaline transfers: fast rides, scary films, spicy food challenges, competitive games — the arousal of excitement gets attributed to you (misattribution of arousal — real psychology). Structure: activity with energy → wind-down with depth. The date tells the emotional story so you don\'t have to force it.',
  },
  {
    id: 'rollercoaster-absence',
    category: 'Emotional Contrast',
    phase: 'ongoing',
    cheat_sheet_essential: false,
    short_form: 'Absence is part of the ride — a quiet day after an intense evening creates thinking-about-you.',
    long_form: 'An intense, brilliant evening followed by a quiet day is the rhythm that creates thinking-about-you. Constant contact flattens the wave.',
  },
  {
    id: 'rollercoaster-hardline',
    category: 'Emotional Contrast',
    phase: 'ongoing',
    cheat_sheet_essential: false,
    short_form: 'The hard line: variance in fun and depth, never in respect or reliability.',
    long_form: 'Hot-cold on "do I actually care about you" isn\'t a rollercoaster, it\'s manipulation, and it attracts anxious attachment, not love. Be a rollercoaster of experiences and a rock of character — that combination is rare and it\'s the whole formula.',
  },

  // ---- Scarcity ----
  {
    id: 'chase-principle',
    category: 'Scarcity',
    phase: 'ongoing',
    cheat_sheet_essential: false,
    short_form: 'Pursuit follows value + scarcity — build real scarcity, not a fake timer.',
    long_form: 'People chase what\'s valuable AND not fully available. Fake scarcity (ignoring texts on a timer) collapses the moment she gets bored; real scarcity — a genuinely full life — only gets more attractive the closer she looks. Build the real version.',
  },
  {
    id: 'chase-building',
    category: 'Scarcity',
    phase: 'ongoing',
    cheat_sheet_essential: false,
    short_form: 'Actually be building something — purpose is the aphrodisiac, busyness is just its side effect.',
    long_form: 'The gym, the football, the money skills, this whole app\'s contents — a man with a mission has natural slow replies because he\'s genuinely mid-set, mid-session, mid-work. "Sorry, was training" hits different when it\'s true and their Instagram confirms it.',
  },
  {
    id: 'chase-reply-pace',
    category: 'Scarcity',
    phase: 'ongoing',
    cheat_sheet_essential: true,
    short_form: 'Reply pace: calibrated, not calculated — respond when you actually surface.',
    long_form: 'Don\'t be glued to your phone answering in 30 seconds, and don\'t run a 3-hour timer either. Natural rhythm: respond when you actually surface from what you\'re doing. Quality of reply beats speed — one funny, specific message after 2 hours beats five instant "lol"s.',
  },
  {
    id: 'chase-end-first',
    category: 'Scarcity',
    phase: 'ongoing',
    cheat_sheet_essential: false,
    short_form: 'End interactions first (sometimes) — leave the conversation at its peak.',
    long_form: 'Leave the conversation at its peak — "right, gym calls. Continue this Thursday." The person who ends the interaction on a high is the one who gets thought about. Never abruptly, never as punishment.',
  },
  {
    id: 'chase-invest',
    category: 'Scarcity',
    phase: 'ongoing',
    cheat_sheet_essential: true,
    short_form: 'Let her invest — leave space for her to text first and suggest plans.',
    long_form: 'Chasing dies when you do 100% of the work. After you\'ve led the start, leave space: let her text first sometimes, ask you questions, suggest the next plan. People value what they invest in. If you always fill every gap, there\'s nothing for her to reach for.',
  },
  {
    id: 'chase-visible',
    category: 'Scarcity',
    phase: 'ongoing',
    cheat_sheet_essential: false,
    short_form: 'Be visibly desired, quietly — pre-selection is the strongest trigger, but never performed.',
    long_form: 'A social life with women friends, group photos, stories of a full life — pre-selection is the strongest attraction trigger there is. Never flaunt it at her or name-drop other girls; the signal works because it\'s ambient, not performed.',
  },
  {
    id: 'chase-warmth',
    category: 'Scarcity',
    phase: 'ongoing',
    cheat_sheet_essential: false,
    short_form: 'Warmth when present, gone when gone — not lukewarm-always.',
    long_form: 'The combination that creates chase: fully engaged, magnetic attention when you\'re with her — then genuinely absorbed in your life when you\'re not. Hot-present/cold-absent, not lukewarm-always. Constant mediocre contact kills more attraction than distance ever has.',
  },
  {
    id: 'chase-line',
    category: 'Scarcity',
    phase: 'ongoing',
    cheat_sheet_essential: false,
    short_form: 'All of this only works from abundance — and reward it once she IS chasing.',
    long_form: 'If you\'re staring at your phone calculating minutes, you\'re chasing — just silently. Go train, go build, and let the fullness be real. And once she IS chasing and you like her — reward it. Punishing interest she shows is how you lose the ones worth keeping.',
  },

  // ---- Closing ----
  {
    id: 'nightsout-close',
    category: 'Closing',
    phase: 'closing',
    cheat_sheet_essential: true,
    short_form: 'Close honestly — number early once it\'s clearly on, exit like a king if it\'s not.',
    long_form: 'Number early once it\'s clearly on ("we\'re getting food this week — what\'s your number?"), because clubs eat conversations. If the vibe is instant, suggest the food spot after. And if she\'s hesitant at ANY step — smile, wish her a good night, exit like a king. The whole room notices how you handle a no.',
  },
  {
    id: 'numbers-peak',
    category: 'Closing',
    phase: 'closing',
    cheat_sheet_essential: true,
    short_form: 'Ask at the peak, not the fizzle — assumptive, warm, simple.',
    long_form: '"I need to run — but I want to continue this. What\'s your number?" Assumptive, warm, simple.',
  },
  {
    id: 'numbers-purpose',
    category: 'Closing',
    phase: 'ongoing',
    cheat_sheet_essential: false,
    short_form: 'Text with purpose the next day — callback, then propose something concrete.',
    long_form: 'Callback to your conversation within a day ("found the song you butchered at karaoke"), then propose something concrete: day, time, place. Endless texting kills momentum.',
  },
  {
    id: 'numbers-stories',
    category: 'Closing',
    phase: 'ongoing',
    cheat_sheet_essential: false,
    short_form: 'Plan dates that create stories — movement and novelty do the bonding for you.',
    long_form: 'Walk + street food + a view beats a staring contest over dinner. Movement and novelty do the bonding for you.',
  },
  {
    id: 'numbers-release',
    category: 'Closing',
    phase: 'closing',
    cheat_sheet_essential: false,
    short_form: 'If she\'s hesitant or goes quiet — release gracefully, every time.',
    long_form: '"No stress at all — enjoy your week." Chasing communicates scarcity; grace communicates options. And it\'s just the right way to treat people.',
  },

  // ---- Taking Her Home ----
  {
    id: 'home-prereq',
    category: 'Taking Her Home',
    phase: 'closing',
    cheat_sheet_essential: false,
    short_form: 'Prerequisites, honestly — only if the whole night built it and both of you are sober.',
    long_form: 'This only happens when the whole night built it: strong connection, escalating vibe, her matching your energy at every step. You can\'t "technique" someone home who isn\'t feeling it — and both of you need to be sober enough that it\'s a real choice. If she\'s drunk past clear judgement, the strong move is her number and a proper date; that restraint reads as class AND gets the girl more often than the push does.',
  },
  {
    id: 'home-bridge',
    category: 'Taking Her Home',
    phase: 'conversation',
    cheat_sheet_essential: false,
    short_form: 'Build the bridge early — plant a story so "coming back" has an easy yes attached.',
    long_form: 'Mid-conversation, plant seeds naturally: mention your amazing rooftop view, the vinyl collection, that you make the best 2am toastie in the city. Now "coming back" has a story attached that isn\'t just the obvious — it gives her a comfortable yes to say.',
  },
  {
    id: 'home-invitation',
    category: 'Taking Her Home',
    phase: 'closing',
    cheat_sheet_essential: false,
    short_form: 'The invitation: casual, specific, low-pressure — one ask, zero sulk if it\'s a no.',
    long_form: 'Near the night\'s peak (not closing time desperation): "I\'m heading back to mine — come see the view / for a drink." Light tone, direct intent. One ask. If it\'s "I shouldn\'t / not tonight" — "fair, then let me take your number and do this properly." Zero sulk.',
  },
  {
    id: 'home-logistics',
    category: 'Taking Her Home',
    phase: 'closing',
    cheat_sheet_essential: false,
    short_form: 'Logistics are seduction — clean place, easy Uber, water in the fridge.',
    long_form: 'Uber ordered in one tap, you know your address flow, place is CLEAN (the state of your room has ended more nights than rejections have). Water and snacks in the fridge. The guy whose life is together at 2am is rare.',
  },
  {
    id: 'home-friends',
    category: 'Taking Her Home',
    phase: 'closing',
    cheat_sheet_essential: false,
    short_form: 'Friends checkpoint — encourage her safety check, it makes you the safe option.',
    long_form: 'She\'ll often check with friends — encourage it, don\'t fight it: "make sure your mates know where you are." Supporting her safety check makes YOU the safe option and defuses friend-blocking.',
  },
  {
    id: 'home-nolunge',
    category: 'Taking Her Home',
    phase: 'escalation',
    cheat_sheet_essential: false,
    short_form: 'Back at yours: no lunging — keep the night\'s energy, let it build naturally.',
    long_form: 'Keep the night\'s energy — music on, the drink/toastie you promised, show the view. Sit close, keep the flirt running, let it build to a kiss naturally. The rush communicates "the talking was fake"; the patience communicates the opposite.',
  },
  {
    id: 'home-final-no',
    category: 'Taking Her Home',
    phase: 'closing',
    cheat_sheet_essential: true,
    short_form: 'Any no along the way is final and fine — instant, cheerful acceptance, every time.',
    long_form: 'A no to coming back, a no to anything at yours — instant, cheerful acceptance. Aftercare applies to the whole night: whatever happens, she gets home safe, and the next-day text isn\'t cold. That\'s the reputation that keeps working long after tonight.',
  },

  // ---- Relationship ----
  {
    id: 'gf-screen',
    category: 'Relationship',
    phase: 'ongoing',
    cheat_sheet_essential: false,
    short_form: 'Screen, don\'t just chase — you\'re choosing too.',
    long_form: 'Watch for: how she treats waiters, whether she asks about you, reliability (does she flake?), how she talks about exes, whether her life has its own engine. Beauty gets someone dates; character gets them a relationship.',
  },
  {
    id: 'gf-consistency',
    category: 'Relationship',
    phase: 'ongoing',
    cheat_sheet_essential: false,
    short_form: 'Consistency is the courtship — one date a week, escalating in depth.',
    long_form: 'One date a week minimum, planned by you, escalating in depth: activity date → dinner → cooking at yours → meeting friends. Momentum with patience — rushing reads as scarcity, drifting reads as indifference.',
  },
  {
    id: 'gf-depth',
    category: 'Relationship',
    phase: 'ongoing',
    cheat_sheet_essential: false,
    short_form: 'Depth trades build the bond — you lead the vulnerability, she matches.',
    long_form: 'Each date, exchange something realer: fears, family, ambitions, embarrassments. You lead the vulnerability, she matches. That ladder IS falling for each other.',
  },
  {
    id: 'gf-material',
    category: 'Relationship',
    phase: 'ongoing',
    cheat_sheet_essential: false,
    short_form: 'Be boyfriend material before asking for the title.',
    long_form: 'Emotional steadiness, keeping plans, remembering details, having your own mission (gym, money, football). The relationship conversation goes well when it\'s obvious you\'re a catch committing, not a fan hoping.',
  },
  {
    id: 'gf-exclusivity',
    category: 'Relationship',
    phase: 'ongoing',
    cheat_sheet_essential: false,
    short_form: 'The exclusivity talk — direct, relaxed, no ultimatums, no hint-dropping.',
    long_form: 'After 6-10 great dates when it\'s clearly mutual: "I\'m not interested in seeing anyone else — I want this to be us. What do you think?" If she hesitates, don\'t negotiate; take it as information.',
  },
  {
    id: 'gf-redflags',
    category: 'Relationship',
    phase: 'ongoing',
    cheat_sheet_essential: false,
    short_form: 'Red flags override chemistry — walking away early is a skill that saves years.',
    long_form: 'Contempt, chronic flaking, secret-keeping, punishing you with silence — attraction makes these easy to excuse and they only grow. Walking away early is a skill that saves years.',
  },

  // ---- Intimacy ----
  {
    id: 'intimacy-consent',
    category: 'Intimacy',
    phase: 'escalation',
    cheat_sheet_essential: false,
    short_form: 'Consent and communication are the foundation — and they\'re attractive.',
    long_form: 'Enthusiastic yes at every stage, and check-ins that double as dirty talk ("you like that?"). A partner who clearly cares about her experience is rarer and hotter than any technique. If she\'s hesitant or drunk, the move is always to slow down or stop.',
  },
  {
    id: 'intimacy-slow',
    category: 'Intimacy',
    phase: 'escalation',
    cheat_sheet_essential: false,
    short_form: 'Slow is the cheat code — the #1 mistake is rushing.',
    long_form: 'Kissing, neck, ears, inner thighs — build for far longer than feels necessary. Arousal for her is a slow curve, and the buildup decides everything that follows. Teasing (approaching, retreating) beats grabbing.',
  },
  {
    id: 'intimacy-technique',
    category: 'Intimacy',
    phase: 'escalation',
    cheat_sheet_essential: false,
    short_form: 'Technique over enthusiasm — rhythm and consistency beat speed and force.',
    long_form: 'Start outside, gentle circles, light pressure first. Wetness first, always — if she\'s not, more kissing and buildup, never force. Rhythm and consistency beat speed and force — when something makes her respond, keep doing exactly that; changing it up at the peak is the classic error.',
  },
  {
    id: 'intimacy-read',
    category: 'Intimacy',
    phase: 'escalation',
    cheat_sheet_essential: false,
    short_form: 'Read her, not a script — her body gives constant feedback.',
    long_form: 'Breathing quickening, hips moving toward you, hands pulling you in = continue. Stillness, tensing up, pulling back = change or pause and check in softly.',
  },
  {
    id: 'intimacy-pace',
    category: 'Intimacy',
    phase: 'escalation',
    cheat_sheet_essential: false,
    short_form: 'Pace and presence matter more than speed — angles matter more than speed.',
    long_form: 'Start slower than you think, full attention on her reactions. Positions where she controls depth, or where there\'s clitoral contact/access, are how most women actually finish — penetration alone often isn\'t.',
  },
  {
    id: 'intimacy-lasting',
    category: 'Intimacy',
    phase: 'escalation',
    cheat_sheet_essential: false,
    short_form: 'Lasting longer — slow breathing, vary pace before the edge, focus on her.',
    long_form: 'Slow your breathing (long exhales), vary pace before you\'re at the edge not after, switch positions to reset, and focus on her. Nerves cause most early finishes — experience and comfort fix more than any trick.',
  },
  {
    id: 'intimacy-aftercare',
    category: 'Intimacy',
    phase: 'ongoing',
    cheat_sheet_essential: false,
    short_form: 'Aftercare is part of it — staying close, no phone-grab, is what she remembers.',
    long_form: 'The minutes after — staying close, warmth, no phone-grab — are what she remembers and retells. Cold exits undo everything the rest did.',
  },
  {
    id: 'intimacy-protection',
    category: 'Intimacy',
    phase: 'escalation',
    cheat_sheet_essential: false,
    short_form: 'Protection every time until exclusive and tested — the confident-guy move.',
    long_form: 'Condoms are non-negotiable with new partners. This is the confident-guy move, not the buzzkill.',
  },
];
